<?php

/**
 * @file
 * Contains par_inspection_feedback_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_inspection_feedback_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_inspection_feedback_test module.
    case 'help.page.par_inspection_feedback_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test data for the PAR Data model') . '</p>';
      return $output;

    default:
  }
}
