<?php

/**
 * @file
 * Contains par_header.module.
 */

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_ckeditor_css_alter().
 *
 * Injects our CSS sheets anytime CKEditor has loaded.
 */
function par_ckeditor_ckeditor_css_alter(array &$css, Editor $editor) {
  if (!$editor->hasAssociatedFilterFormat()) {
    return;
  }

  $known_formats = [
    'basic_html',
    'full_html',
  ];

  if (in_array($editor->getFilterFormat()->id(), $known_formats)) {
    $file_name = drupal_get_path('theme', 'par_theme') . '/css/ckeditor.css';
    $css[] = $file_name . '?' . hash_file('md5', $file_name);
  }
}
