<?php

/**
 * @file
 * Contains par_subscriptions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\govuk_cookies\Form\CookieConsentForm;

/**
 * Implements hook_help().
 */
function govuk_cookies_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_subscriptions module.
    case 'help.page.govuk_cookies':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides cookie consent forms for cookie pages to allow users to opt-out of non-essential cookies.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function govuk_cookies_theme() {
  $name = \Drupal::config('system.site')->get('name');
  // @TODO Replace with configurable cookie types.
  $cookie_policy = ['analytics', 'functional', 'other'];

  $message = [
    [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => 'We use some essential cookies to make this service work.',
    ]
  ];
  if (!empty($cookie_policy) && count($cookie_policy) === 1 && current($cookie_policy) === 'analytics') {
    $message[] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => 'We’d also like to use analytics cookies so we can understand how you use the service and make improvements.',
    ];
  }
  elseif (!empty($cookie_policy)) {
    $message[] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => 'We’d like to set additional cookies so we can remember your settings, understand how people use the service and make improvements.',
    ];
  }

  return [
    'govuk_cookie_message' => [
      'variables' => [
        'attributes' => [],
        'title' => "Cookies for $name",
        'message' => $message,
        'cookie_policy' => $cookie_policy,
        'cookie_name' => CookieConsentForm::COOKIE_NAME,
        'cookie' => false,
        'acceptance_message' => 'govuk-cookies-accepted',
        'rejection_message' => 'govuk-cookies-rejected',
      ],
      'template' => 'govuk-cookie-message',
    ]
  ];
}

/**
 * Implements hook_preprocess_govuk_cookie().
 */
function govuk_cookies_preprocess_govuk_cookie_message(&$variables) {
  $request = \Drupal::request();
  $variables['cookie'] = $request->cookies->get(CookieConsentForm::COOKIE_NAME);

  $variables['attributes']['class'] = ['govuk-cookie-banner__message', 'govuk-width-container'];
}
