<?php

/**
 * @file
 * Contains par_model.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_model_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_model module.
    case 'help.page.par_model':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The data model for PAR.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function par_model_theme() {
  return [
    'par_model' => [
      'render element' => 'children',
    ],
  ];
}
