<?php

/**
 * @file
 * Contains par_deviation_review_flows.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_deviation_review_flows_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_deviation_review_flows module.
    case 'help.page.par_deviation_review_flows':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows primary authority officers to review a deviation request sent to them.') . '</p>';
      return $output;

    default:
  }
}
