<?php

/**
 * @file
 * Contains par_styleguide.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_styleguide_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_styleguide module.
    case 'help.page.par_styleguide':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Describes all the components and their styles according to the GOV.UK style guidelines') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function par_styleguide_theme($existing, $type, $theme, $path) {
  return [
    'par_styleguide' => [
      'variables' => ['sections' => NULL],
    ],
    'par_styleguide_data' => [
      'variables' => ['sections' => NULL],
    ],
    'par_styleguide_pagination' => [
      'variables' => ['sections' => NULL],
    ],
    'par_styleguide_components' => [
      'variables' => ['sections' => NULL],
    ]
  ];
}
