<?php

/**
 * @file
 * Contains par_data_entities.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_data_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_data_entities module.
    case 'help.page.par_data_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The data model for PAR.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function par_data_entities_theme() {
  return [
    'par_data_entities' => [
      'render element' => 'children',
    ],
  ];
}
