<?php

/**
 * @file
 * Contains par_subscriptions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_cookies_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_subscriptions module.
    case 'help.page.par_cookies':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides cookie consent forms for cookie pages to allow users to opt-out of non-essential cookies.') . '</p>';
      return $output;

    default:
  }
}
