<?php

/**
 * @file
 * Contains demo_migration.module..
 */

function par2_db_query() {
  // Switch to external database
  \Drupal\Core\Database\Database::setActiveConnection('par2');

  // Get a connection going
  $db = \Drupal\Core\Database\Database::getConnection();

  $query = $db->select('par_documents', 'docs')
    ->fields('docs', ['document_id', 'size_in_bytes', 'file_type'])
    ->orderBy('size_in_bytes', 'asc')
    ->condition('size_in_bytes', 10000, '>');
  $records = $query->execute();

  echo $records->rowCount();

  // Switch back
  \Drupal\Core\Database\Database::setActiveConnection();

  return $records;
}
