<?php
/**
 * @file
 * Installation hooks for par_data_test module.
 */

/**
 * Implements hook_install().
 */
function par_data_test_install() {
  // Create the test entities.
  par_data_test_create_entities();
}

/**
 * Implements hook_uninstall().
 */
function par_data_test_uninstall() {
  // Delete all the entities when we uninstall.
  // Must be removed before we do the final migration.
  // This should just be used for testing while we
  // have no other content in the database.
  $par_data_manager = \Drupal::service('par_data.manager');
  $uuids_to_delete = [
    '65b1f3b2-5e95-4b73-8a81-f536e6a24530', // advice_1
    '63f0deec-353d-4cfb-a727-c372d1b730a6', // inspection_plan_1
    '66a1618f-e4e5-4232-979a-0f8832dd51b0', // legal_entity_1
    '20a5a1a6-4e6c-4c71-b034-f78bd916e397', // legal_entity_2
    '7f3b87cd-4406-4f07-a562-ee6876774b16', // premises_1
    '30fe2400-4deb-411c-98a2-a5935615bd98', // premises_2
    '6be6938f-0350-4705-8d41-a8744cfd2053', // premises_3
    'c42727fb-e6c2-4241-9da7-a0074477f7a7', // premises_4
    '7c3f359d-1ef9-43a3-be5e-883f3beb30cf', // premises_5
    'c78b0352-15c8-42b5-b22d-082b72c51af4', // authority_person_1
    '512ccfa3-496d-47aa-9a46-6abfa8922625', // authority_person_2
    '26db3fbe-d4a6-4a6a-ad69-108b54e1e4c5', // business_person_3
    '3f21083a-98c9-440e-92b0-12947f799e0a', // business_person_4
    'b36d8ee5-b8ff-4dd7-9851-303c66a3497a', // coordinator_person_5
    '8cbcde93-3a33-45ff-9503-02ce78d9a46f', // coordinator_person_6
    'd2f48b3a-799c-43ca-ae08-8df30ecbbfbc', // business_person_7
    '2705c28a-8ee6-4b4d-be80-93b11be48937', // authority_person_8
    '86bcff9c-882e-46d1-b768-68eb5b311f2c', // sic_code_1
    '0f59d76d-3062-4c5e-8b26-b0a798a7104c', // sic_code_1
    '12392d50-57dc-48c8-9480-85f44c9b2903', // organisation_1
    'b3f26aa8-a857-4829-8306-6c88e1fb03f7', // organisation_2
    'adc67edf-a95f-4adc-8332-551589dbb63e', // organisation_3
    '3a4c6455-7263-4f0b-966a-24b8dd518f49', // regulatory_function_1
    '15660610-03e4-47f4-b26e-159d0cd4d86a', // regulatory_function_2
    '2cf01633-9b41-4f65-b5cf-e6ea39df7aba', // authority_1
    '5385e5cf-1b98-43ae-9a3e-e369091a61ef', // authority_2
    '3185889b-a264-4bfe-97ae-1a481f4902a0', // partnership_1
    '7b9f5a2c-d364-4475-a31e-a87db11acad4', // partnership_2
  ];
  foreach ($par_data_manager->getParEntityTypes() as $entity_type => $entity_definition) {
    var_dump($entity_type);
    $entity_storage = $par_data_manager->getEntityTypeStorage($entity_definition);
    foreach ($entity_storage->loadMultiple() as $entity) {
      $entity->delete();
    }
  }

  // We also want to delete all files when we uninstall the module.
  $path = DRUPAL_ROOT . '/' . Drupal::service('module_handler')
      ->getModule('par_data_test')->getPath() . '/assets/';
  $files = scandir($path);
  if (!$files) {
    $files = [];
  }
  foreach (\Drupal::entityTypeManager()->getStorage('file')->loadMultiple() as $file) {
    if (in_array($file->getFilename(), $files)) {
      $file->delete();
    }

  }

  $users = \Drupal::entityTypeManager()->getStorage('user')
    ->loadByProperties(['name' => [
      'par_authority@example.com',
      'par_coordinator@example.com',
      'par_business@example.com',
      'par_helpdesk@example.com',
    ]]);
  foreach ($users as $user) {
    $user->delete();
  }

}
