<?php

/**
 * @file
 * Contains par_components.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_components_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_components module.
    case 'help.page.par_components':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides reusable components throughout the site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function par_components_theme($existing, $type, $theme, $path) {
  return [
    'par_components_business_name_address' => [
      'variables' => [
        'name' => NULL,
        'address' => NULL
      ],
    ],
    'par_components_business_primary_contact' => [
      'variables' => [
        'name' => NULL,
        'telephone' => NULL,
        'email' => NULL,
        'role' => NULL
      ],
    ],
  ];
}
