<?php

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Link;
use Drupal\par_data\Entity\ParDataPerson;

/**
 * Implements hook_token_info().
 */
function par_actions_token_info() {
  $info = [];
  $info['types']['par'] = [
    'name' => t('PAR'),
    'description' => ('PAR data tokens.'),
  ];

  $info['tokens']['par']['par:member-name'] = [
    'name' => t('PAR member name'),
    'description' => t('Name of the PAR Member.'),
    'dynamic' => TRUE,
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 */
function par_actions_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'par') {

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'member-name':
          if ($data['par'] instanceof ParDataPerson) {
            $replacements[$original] = $data['par']->getFullName();
          }
          break;

        default:
      }
    }
  }

  return $replacements;
}
