<?php

/**
 * @file
 * Contains par_data.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_data_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_data module.
    case 'help.page.par_data':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The data model for PAR.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function par_data_theme() {
  return [
    'par_data' => [
      'render element' => 'children',
    ],
    'par_data_entity_list' => [
      'render element' => 'types',
      'variables' => [
        'types' => NULL,
      ],
      'template' => 'par-data-entity-list',
    ],
  ];
}
