version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0

references:
  defaults: &defaults
    docker:
      - image: beispar/web:v3.1.0
        name: web
        environment:
          APP_ENV: ci
          SENTRY_ENVIRONMENT: ci

      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: par
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: par

    environment:
      TEST_REPORTS: ~/par/tests/reports
      S3_ARTIFACTS_BUCKET: beis-par-artifacts
      SANITISED_DATABASE: db-dump-production-sanitised
      UNSANITISED_DATABASE: db-dump-production-unsanitised
      SIMPLETEST_DB: pgsql://par:123456@localhost:5432/par

    working_directory: /var/www/html

  clean_working_directory: &clean_working_directory
    run:
      name: "Clean the default directory"
      command: |
        cd /
        rm -fr /var/www/html/
        mkdir -p /var/www/html/

  restore_code: &restore_code
    restore_cache:
      keys:
        - v10-repo-{{ .Branch }}-{{ .Revision }}

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - v10-dependencies-{{ checksum "composer.lock" }}-{{ checksum "package-lock.json" }}--{{ checksum "web/themes/custom/par_theme/par_theme.libraries.yml" }}--{{ checksum "web/themes/custom/par_theme/par_theme.info.yml" }}

  restore_scaffold: &restore_scaffold
    run:
      name: "Install drupal scaffold files"
      command: |
        composer drupal:scaffold

  configure_webroot: &configure_webroot
    run:
      name: "Configure web root"
      command: |
        sudo chown -RhL www-data:www-data /var/www/html/web
        ls -lah /var/www/html/web
        a2ensite par.localhost
        service apache2 restart
        echo 127.0.0.1 par.localhost | sudo tee -a /etc/hosts
        cat /etc/hosts

  configure_theme: &configure_theme
    run:
      name: "Configure the appropriate theme."
      command: |
        echo "THEME_VERSION=<<parameters.theme_version>>" >> .env
        echo "Enabled theme: $THEME_VERSION"
      environment:
        THEME_VERSION: <<parameters.theme_version>>

  import_database: &import_database
    run:
      name: "Import & set up the database"
      command: |
        cd web
        ../vendor/bin/drush @par.dev sql:cli < ../backups/${SANITISED_DATABASE}.sql
        ../drupal-update.sh

  build_assets: &build_assets
    run:
      name: "Make asset bundle"
      command: |
        cd /tmp/workspace
        echo "{ \"build\" : \"${CIRCLE_BUILD_NUM}\", \"tag\":\"${CIRCLE_TAG}\", \"time\":\"$(date -u)\"}" > web/build_version.txt
        echo "SENTRY_RELEASE=$CIRCLE_TAG" >> .env
        tar -zcf /tmp/$CIRCLE_TAG.tar.gz .

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - *clean_working_directory
      - *restore_code
      - checkout:
          post:
            - git fetch --tags
      - run:
          name: "Export environment variables"
          command: |
            echo "S3_REGION=$S3_REGION" >> .env
            echo "S3_ACCESS_KEY=$S3_ACCESS_KEY" >> .env
            echo "S3_SECRET_KEY=$S3_SECRET_KEY" >> .env
            echo "S3_BUCKET_ARTIFACTS=$S3_BUCKET_ARTIFACTS" >> .env
            echo "S3_BUCKET_PRIVATE=$S3_BUCKET_PRIVATE" >> .env
            echo "S3_BUCKET_PUBLIC=$S3_BUCKET_PUBLIC" >> .env
            echo "PAR_HASH_SALT=$PAR_HASH_SALT" >> .env
            echo "APP_ENV=$APP_ENV" >> .env
            echo "SENTRY_ENVIRONMENT=$APP_ENV" >> .env
            echo "SENTRY_DSN=$SENTRY_DSN" >> .env
            echo "SENTRY_DSN_PUBLIC=$SENTRY_DSN_PUBLIC" >> .env
            echo "PAR_GOVUK_NOTIFY_KEY=$PAR_GOVUK_NOTIFY_KEY" >> .env
            echo "PAR_GOVUK_NOTIFY_TEMPLATE=$PAR_GOVUK_NOTIFY_TEMPLATE" >> .env
            echo "CLAMAV_HTTP_USER=$CLAMAV_HTTP_USER" >> .env
            echo "CLAMAV_HTTP_PASS=$CLAMAV_HTTP_PASS" >> .env
      - run:
          name: "Database preparation"
          command: |
            mkdir -p backups
      - aws-s3/copy:
          from: "s3://${S3_ARTIFACTS_BUCKET}/backups/${SANITISED_DATABASE}-latest.tar.gz"
          to: backups/${SANITISED_DATABASE}-latest.tar.gz
          arguments: |
            --region eu-west-1 \
            --cache-control "max-age=0"
      - run:
          name: "Unpacking database"
          command: cd backups && tar --no-same-owner -zxvf ${SANITISED_DATABASE}-latest.tar.gz
      - save_cache:
          key: v10-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  compile_code:
    <<: *defaults
    steps:
      - *clean_working_directory
      - *restore_code
      - *restore_dependencies
      - run:
          name: "Installing app"
          command: |
            echo "$(pwd)"
            composer install -v
            rm -f web/themes/contrib/govuk_theme/css/styles.css
            npm run install-govuk-theme
            npm run install-par-theme
            npm install
            npm run gulp
      - run:
          name: "Installing tests"
          command: |
            echo "$(pwd)"
            cd ./tests && rm -rf node_modules && npm install
      - *restore_scaffold
      - save_cache:
          key: v10-dependencies-{{ checksum "composer.lock" }}-{{ checksum "package-lock.json" }}--{{ checksum "web/themes/custom/par_theme/par_theme.libraries.yml" }}--{{ checksum "web/themes/custom/par_theme/par_theme.info.yml" }}
          paths:
            - ./node_modules
            - ./vendor
            - ./web/core
            - ./web/libraries
            - ./web/modules/contrib
            - ./web/profiles/contrib
            - ./web/themes/contrib
            - ./web/themes/custom
            - ./drush/contrib
      - run:
          name: "Create workspace"
          command: |
            mkdir -p /tmp/workspace
            cp -rT . /tmp/workspace
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test_smoke:
    <<: *defaults
    parameters:
      theme_version:
        description: "The theme version to test."
        default: v1
        type: string
    steps:
      - *clean_working_directory
      - *restore_code
      - *restore_dependencies
      - *restore_scaffold
      - *configure_webroot
      - *configure_theme
      - *import_database
      - run:
          name: "Run cron"
          command: |
            cd web
            ../vendor/bin/drush cron
            ../vendor/bin/drush cron
            ../vendor/bin/drush cron
      - run:
          name: "Application checklist"
          command: |
            cd web
            ../vendor/bin/drush --no config:import
            ../vendor/bin/drush core-requirements --severity=2
            ../vendor/bin/drush ev "print_r(\Drupal::service('flysystem_factory')->ensure());"
            curl -sD - -o /dev/null http://par.localhost
      - run:
          name: "Install test dependencies"
          command: |
            cd tests
            mkdir -p ./reports/phpunit
            mkdir -p ./reports/nightwatch
            npm install
            npm run selenium-install
      - run:
          name: "Run unit tests"
          command: |
            ./vendor/bin/paratest --processes=16
      - run:
          name: "Run feature tests"
          command: |
            cd tests
            echo "Running tests against theme: <<parameters.theme_version>>"
            npm run ci-<<parameters.theme_version>> -- --tag <<parameters.theme_version>>-ci
            npm run generate-report
      # Save artifacts
      - store_artifacts:
          path: /var/www/html/tests/reports
          destination: build
      # Upload test results
      - store_test_results:
          path: /var/www/html/tests/reports

  test_full:
    <<: *defaults
    parameters:
      theme_version:
        description: "The theme version to test."
        default: v1
        type: string
    steps:
      - *clean_working_directory
      - *restore_code
      - *restore_dependencies
      - *restore_scaffold
      - *configure_webroot
      - *configure_theme
      - *import_database
      - run:
          name: "Run cron"
          command: |
            cd web
            ../vendor/bin/drush cron
      - run:
          name: "Application checklist"
          command: |
            cd web
            ../vendor/bin/drush --no config:import
            ../vendor/bin/drush core-requirements --severity=2
            curl -sD - -o /dev/null http://par.localhost
      - run:
          name: "Install test dependencies"
          command: |
            cd tests
            mkdir -p ./reports/phpunit
            mkdir -p ./reports/nightwatch
            npm install
            npm run selenium-install
      - run:
          name: "Run unit tests"
          command: |
            ./vendor/bin/paratest --processes=16
      - run:
          name: "Run feature tests"
          command: |
            cd tests
            echo "Running tests against theme: <<parameters.theme_version>>"
            npm run ci-<<parameters.theme_version>> -- --tag <<parameters.theme_version>>-ci
            npm run generate-report
      # Save artifacts
      - store_artifacts:
          path: /var/www/html/tests/reports
          destination: build
      # Upload test results
      - store_test_results:
          path: /var/www/html/tests/reports

  deploy_stage:
    <<: *defaults
    steps:
      - *clean_working_directory
      - *attach_workspace
      - *restore_code
      - *restore_dependencies
      - *restore_scaffold
      - *configure_webroot
      - *import_database
      - *build_assets
      - run:
          name: "Examine asset bundle."
          command: |
            ls -lah /tmp/workspace
      - aws-s3/copy:
          from: /tmp/${CIRCLE_TAG}.tar.gz
          to: "s3://${S3_ARTIFACTS_BUCKET}/builds/${CIRCLE_TAG}.tar.gz"
          arguments: |
            --region eu-west-1 \
            --cache-control "max-age=0"
      - run:
          name: "Deploy to staging environment"
          command: |
            DEPLOY_ENV="staging"
            printf "$DEPLOY_ENV\n"
            ./devops/cf/push.local.sh -T $CIRCLE_TAG -r -b /var/www/html/backups/${SANITISED_DATABASE}.sql -d /tmp/workspace $DEPLOY_ENV

  deploy_prod:
    <<: *defaults
    steps:
      - *clean_working_directory
      - *attach_workspace
      - *restore_code
      - *restore_dependencies
      - *restore_scaffold
      - *configure_webroot
      - *import_database
      - run:
          name: "Remove additional sensitive assets"
          command: |
            cd /tmp/workspace
            rm -fr backups
      - *build_assets
      - run:
          name: "Examine asset bundle"
          command: |
            ls -lah /tmp/workspace
      - run:
          name: "Deploy to production environment"
          command: |
            DEPLOY_ENV="production"
            printf "$DEPLOY_ENV\n"
            ./devops/cf/push.local.sh -T $CIRCLE_TAG -u $GOVUK_CF_USER -p $GOVUK_CF_PWD -x -d /tmp/workspace -i 4 $DEPLOY_ENV

  deploy_test:
    <<: *defaults
    steps:
      - *clean_working_directory
      - *attach_workspace
      - *restore_code
      - *restore_dependencies
      - *restore_scaffold
      - *configure_webroot
      - *import_database
      - *build_assets
      - run:
          name: "Examine asset bundle."
          command: |
            ls -lah /tmp/workspace
      - aws-s3/copy:
          from: /tmp/${CIRCLE_TAG}.tar.gz
          to: "s3://${S3_ARTIFACTS_BUCKET}/builds/${CIRCLE_TAG}.tar.gz"
          arguments: '--region eu-west-1'
      - run:
          name: "Deploy to test environment"
          command: |
            DEPLOY_ENV=($(echo $CIRCLE_TAG | awk -F '-' '{print $1}'))
            printf "Deploying to test environment: https://beis-par-$DEPLOY_ENV.cloudapps.digital\n"
            ./devops/cf/push.local.sh -T $CIRCLE_TAG -r -b /var/www/html/backups/${SANITISED_DATABASE}.sql -d /tmp/workspace $DEPLOY_ENV

  archive_database:
    <<: *defaults
    steps:
      - run:
          name: "Backup production database"
          command: |
            cf login -a api.cloud.service.gov.uk -u $PROD_GOVUK_CF_USER -p $PROD_GOVUK_CF_PWD
            cf target -o office-for-product-safety-and-standards -s primary-authority-register-production
            cf run-task beis-par-production "./scripts/db-backup.sh production -p" --name DB_ARCHIVE -k 4G -m 4G

  sanitise_database:
    <<: *defaults
    steps:
      - *clean_working_directory
      - *restore_code
      - *restore_dependencies
      - *restore_scaffold
      - *configure_webroot
      - aws-s3/copy:
          from: "s3://${S3_ARTIFACTS_BUCKET}/backups/${UNSANITISED_DATABASE}-latest.tar.gz"
          to: "backups/${UNSANITISED_DATABASE}-latest.tar.gz"
          arguments: |
            --region eu-west-1 \
            --cache-control "max-age=0"
      - run:
          name: "Unpacking database"
          command: cd backups && tar --no-same-owner -zxvf ${UNSANITISED_DATABASE}-latest.tar.gz
      - run:
          name: "Check db archive date"
          command: cd backups && ls -lah ${UNSANITISED_DATABASE}.sql
      - run:
          name: "Importing database"
          command: cd web && sed -e '/-- do not execute if not member of manager role/,+4d' < ../backups/${UNSANITISED_DATABASE}.sql | ../vendor/bin/drush @par.dev sql:cli
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Setup application"
          command: ./drupal-update.sh
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Run cron"
          command: |
            cd web
            ../vendor/bin/drush cron
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Application checklist"
          command: |
            cd web
            ../vendor/bin/drush --no config:import
            ../vendor/bin/drush core-requirements --severity=2
            curl -sD - -o /dev/null http://par.localhost
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Un-install temporary data @temp"
          command: |
            cd web
            ../vendor/bin/drush pm-uninstall par_data_test -y
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Un-install dev only modules"
          command: |
            cd web
            ../vendor/bin/drush pm-uninstall webprofiler -y
            ../vendor/bin/drush pm-uninstall maillog -y
            ../vendor/bin/drush pm-uninstall dblog -y
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Sanitise database"
          command: |
            cd web
            ../vendor/bin/drush @par.paas sql:sanitize -y
          environment:
            APP_ENV: ci-sanitise
      - run:
          name: "Backup database"
          command: ./scripts/db-backup.sh production -s -d "../backups" -a '@par.dev'
          environment:
            APP_ENV: ci-sanitise
      - aws-s3/copy:
          from: "backups/${SANITISED_DATABASE}-latest.tar.gz"
          to: "s3://${S3_ARTIFACTS_BUCKET}/backups/${SANITISED_DATABASE}-latest.tar.gz"
          arguments: |
            --region eu-west-1 \
            --cache-control "max-age=0"

workflows:
  version: 2.1
#  theme_v2_test:
#    jobs:
#      - checkout_code:
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore:
#                - master
#      - compile_code:
#          requires:
#            - checkout_code
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore:
#                - master
#      - test_full:
#          name: test_theme
#          theme_version: v2
#          requires:
#            - compile_code
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore:
#                - master

  build_test_deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
      - compile_code:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
      - test_full:
          requires:
            - compile_code
          filters:
            tags:
              only: /^[a-zA-Z0-9]+.*/
            branches:
              ignore: /.*/
      - hold_stage:
          type: approval
          requires:
            - test_full
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_stage:
          requires:
            - hold_stage
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - hold_prod:
          type: approval
          context: production
          requires:
            - deploy_stage
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_prod:
          context: production
          requires:
            - hold_prod
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test_smoke:
          requires:
            - compile_code
          filters:
            branches:
              ignore:
                - master
      - hold_test:
          type: approval
          requires:
            - compile_code
          filters:
            tags:
              only: /^[a-uw-zA-Z0-9]+.*/
            branches:
              ignore: /.*/
      - deploy_test:
          requires:
            - hold_test
          filters:
            tags:
              only: /^[a-uw-zA-Z0-9]+.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - checkout_code
      - compile_code:
          requires:
            - checkout_code
      - test_full:
          requires:
            - compile_code

  db_archive:
    triggers:
      - schedule:
          cron: "0 0 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - archive_database

  db_sanitise:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - checkout_code
      - compile_code:
          requires:
            - checkout_code
      - sanitise_database:
          requires:
            - compile_code
