package uk.gov.beis.enums;

public enum UsableValues {

		BUSINESS_NAME, 
		BUSINESS_EMAIL,
		BUSINESS_PHONE,
		BUSINESS_POSTCODE,
		BUSINESS_FIRSTNAME,
		BUSINESS_LASTNAME,
		AUTHORITY_ADDRESSLINE1,
		AUTHORITY_POSTCODE,
		AUTHORITY_TYPE,
		AUTHORITY_REGFUNCTION,
		ONS_CODE,
		AUTHORITY_TOWN,
		PARTNERSHIP_INFO,
		ENTITY_NAME,
		PARTNERSHIP_TYPE,
		AUTHORITY_NAME,
		MEMBERLIST_SIZE,
		TRADING_NAME,
		REGISTRATION_NO,
		ENTITY_TYPE,
		INVITE_LINK,
		BUSINESS_ADDRESSLINE1,
		SIC_CODE,
		NO_EMPLOYEES,
		LOGIN_USER,
		BUSINESS_TOWN;
}
