web:
  build: .
  dockerfile: Dockerfile-web
  container_name: pars_beta_web
  links:
    - db
  ports:
    - "8111:80"
  volumes:
    - ../web:/var/www/html
    - ../vendor:/var/www/vendor
db:
  image: mysql:5.6
  container_name: pars_beta_db
  ports:
    - "3111:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: pars
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: pars

