version: "2"

services:
    web:
      image: parbeta/web:v4
      container_name: par_beta_web
      links:
        - db
      ports:
        - "8111:80"
      volumes:
        - ../:/var/www/html

    db:
      container_name: par_beta_db
      restart: always
      image: postgres:9.6.3
      ports:
        - "5411:5432"
      environment:
        POSTGRES_USER: par
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: par

