web:
  build: .
  dockerfile: Dockerfile-web
  container_name: pars_beta_web
  links:
    - db
  ports:
    - "8111:80"
  volumes:
    - ../web:/var/www/html
    - ../vendor:/var/www/vendor
db:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5411:5432"
  environment:
    - DEBUG=false
    - DB_USER=pars
    - DB_PASS=123456
    - DB_NAME=pars
    - DB_TEMPLATE=
    - DB_EXTENSION=
    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=

