# Configuration file schema.
par_data.settings:
  type: config_object
  label: 'Par Data settings'
  mapping:
    stubbed:
      type: boolean
      label: 'Whether to stub the entities when testing.'

# PAR Data Entity types
par_data.par_data_type.*:
  type: config_entity
  label: 'PAR Data entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      lavel: 'Description'
    help:
      type: string
      label: 'Help'
    uuid:
      type: string
    configuration:
      type: par_data.configuration
      nullable: true
      sequence:
        type: sequence
        label: 'Element (entity or field name)'
        nullable: true
        sequence:
          type: sequence
          label: 'Configuration rules'
          nullable: true
          sequence:
            type: mapping
            label: 'Rule'
