# Configuration file schema.
par_data.settings:
  type: config_object
  label: 'Par Data settings'
  mapping:
    stubbed:
      type: boolean
      label: 'Whether to stub the entities when testing.'

# PAR Data Entity types
par_data.par_data_*_type.*:
  type: config_entity
  label: 'PAR Data entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      lavel: 'Description'
    help:
      type: string
      label: 'Help'
    uuid:
      type: string
    configuration:
      type: par_data.configuration
      nullable: true

par_data.configuration:
  type: config_object
  label: 'Configuration elements'
  sequence:
    type: sequence
    label: 'Element (entity or field name)'
    nullable: true
    sequence:
      type: sequence
      label: 'Configuration rules'
      nullable: true
      sequence:
        type: mapping
        label: 'Rule'
        mapping:
          type:
            type: string
            label: 'Value Type'
          name:
            type: string
            label: 'Rule name'
          value:
            type: par_data.configuration_value.[type]

par_data.configuration_value.default:
  type: config_object
  label: 'Default configuration value'
  mapping:
    type:
      type: string
      label: 'String'
    value:
      type: string
      label: 'Default value'

par_data.configuration_value.integer:
  type: config_object
  label: 'Integer configuration value'
  mapping:
    type:
      type: string
      label: 'Integer'
    value:
      type: integer
      label: 'Numeric value'

par_data.configuration_value.map:
  type: config_object
  label: 'Array map configuration value'
  mapping:
    type:
      type: string
      label: 'Map'
    value:
      type: sequence
      label: 'Map keys'
      nullable: true
      sequence:
        type: par_data.configuration_value.[type]
