<?php

/**
 * @file
 * Contains par_search_partnership_flows.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_search_partnership_flows_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_search_partnership_flows module.
    case 'help.page.par_search_partnership_flows':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows enforcement officers to search for partnerships, so that they can be enforced and the primary authorities can be communicated with.') . '</p>';
      return $output;

    default:
  }
}
