<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function par_flow_transition_partnership_details_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Journey 1 Step 1 (List of Partnerships) Views Exposed Filter customisation.
  if ($form['#id'] == 'views-exposed-form-par-data-transition-journey-1-step-1-dv-journey-1-step-1' ||
      $form['#id'] == 'views-exposed-form-rd-helpdesk-dashboard-par-rd-helpdesk-dashboard-page') {

    $form['actions']['submit']['#attributes']['class'][] = 'btn-link';
    $form['actions']['submit']['#value'] = 'Update details';

  }

}
