<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function par_flow_transition_partnership_details_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Views Exposed Filter customisation.
  if ($form['#id'] == 'views-exposed-form-par-data-transition-journey-1-step-1-dv-journey-1-step-1' ||
      $form['#id'] == 'views-exposed-form-rd-helpdesk-dashboard-par-rd-helpdesk-dashboard-page') {

    $form['actions']['submit']['#attributes']['class'][] = 'btn-link';
    $form['actions']['submit']['#value'] = 'Update results';

  }

}

/**
 * Implements hook_views_pre_render().
 *
 * @param \Drupal\views\ViewExecutable $view
 */
function par_flow_transition_partnership_details_views_pre_render(ViewExecutable $view) {

  // Customise RD Helpdesk Dashboard.
  if ($view->current_display == 'par_rd_helpdesk_dashboard_page') {

    // Override CSV Feed icon.
    $feed_icon = &$view->feedIcons[0];

    if (isset($feed_icon)) {

      // Get URL from Drupal Views Data Export module.
      $url = Url::fromUri($feed_icon['#url']);

      // Create link.
      $link = Link::fromTextAndUrl('Download as CSV', $url)->toString();

      // Feed icon as markup.
      $feed_icon = [
        '#type' => 'markup',
        '#markup' => $link,
        '#theme_wrappers' => [
          'container' => [
            '#attributes' => [
              'class' => ['views-data-export-csv-feed']
            ],
          ],
        ],
      ];

    }

  }

}

/**
 * Implements hook_views_query_alter().
 *
 * @param \Drupal\views\ViewExecutable $view
 * @param $query
 */
function par_flow_transition_partnership_details_views_query_alter(ViewExecutable $view, $query) {

  // PostgreSQL case insensitive query alter.
  foreach ($query->where as $group_key => $group) {
    foreach ($group['conditions'] as $key => $condition) {

      // Only apply to combined fields, Views stamps in queries are useful!
      if (preg_match('/:views_combine/', $condition['field'])) {
        // ILIKE is proprietary to PostgreSQL.
        $query->where[$group_key]['conditions'][$key]['field'] = str_replace('LIKE', 'ILIKE', $condition['field']);
      }

    }
  }

}
