@Pending
Feature: User journey

Scenario: User Journey Flow
    Given I open the url "/user/login"
    And I add "TestPassword" to the inputfield "#edit-pass"
    And I add "par_authority@example.com" to the inputfield "#edit-name"
    When I click on the button "#edit-submit"
    Then I expect that element ".error-message" is not visible
    And I open the url "/dv/primary-authority-partnerships/1"
    And I click on the link "Review & confirm"
    Then the element "#edit-first-section" contains the text "Please Review the new Primary Authority terms and conditions and confirm that you agree with them."
    And I click on the checkbox "#edit-terms-conditions"
    And I click on the button "#edit-next"
    And I click on the link "Review and confirm your partnership details"
    And I click on the link "edit"
    And I add "test change information about the partnership" to the inputfield "#edit-about-partnership"
    And I click on the button "#edit-next"
    Then the element "#edit-first-section" contains the text "test change information about the partnership"
    When I open the url "/dv/primary-authority-partnerships/1/partnership/1/details/edit-contact/6"
    And I add "Primarycontactnamechange" to the inputfield "#edit-person-name"
    And I click on the button "#edit-next"
    Then the element "#edit-authority-contacts" contains the text "Primarycontactnamechange"
    When I open the url "/dv/primary-authority-partnerships/1/partnership/1/details/edit-contact/1"
    And I add "Mainbusinesscontactchange" to the inputfield "#edit-person-name"
    And I click on the button "#edit-next"
    Then the element "#edit-organisation-contacts" contains the text "Mainbusinesscontactchange"
    When I open the url "/dv/primary-authority-partnerships/1/partnership/1/details/edit-contact/2"
    And I add "Businesssecondarycontactchange" to the inputfield "#edit-person-name"
    And I click on the button "#edit-next"
    Then the element "#edit-organisation-contacts" contains the text "Businesssecondarycontactchange"
    And I click on the checkbox "#edit-partnership-agreement"
    And I click on the checkbox "#edit-confirmation"
    And I click on the button "#edit-next"
    And I click on the link "Save and continue"
    Then the element "#block-par-theme-content" contains the text "confirmed_authority"
