@Pending @userjourney1
Feature: User Journey 1 (happy path)

Scenario: User Journey 1 (happy path)    
    # HOMEPAGE 
    Given I open the url "/"
    And I click on the link "Log in"
    # LOGIN SCREEN
    And I add "par_authority@example.com" to the inputfield "#edit-name"
    And I add "TestPassword" to the inputfield "#edit-pass"
    When I click on the button "#edit-submit"
    # WELCOME SCREEN
    Then I expect that element ".error-message" is not visible
    When I click on the button ".button-start"
    # PARTNERSHIPS DASHBOARD
    And I click on the link "ABCD Mart"
    # TERMS AND CONDITIONS SCREEN
    And I click on the checkbox "#edit-terms-conditions"
    And I click on the button "#edit-next"
    # PARTERSHIP TASKS SCREEN
    # When I click on the link "Invite the business to confirm their details"
    # # BUSINESS EMAIL INVITATION
    # And I add "Test change meassage body [invite:invite-accept-link]" to the inputfield "#edit-email-body"
    # And I add "Test change meassage subject" to the inputfield "#edit-email-body"
    # And I press "Send Invitation"
    #  # PARTERSHIP TASKS SCREEN
    # Then the element "h1" contains the text "Updating the Primary Authority Register"
    # Then the element "#edit-email-subject" contains the text "Test change subject line"
    # Then the element "#edit-email-body" contains the text "Test change meassage body [invite:invite-accept-link]"
    When I click on the link "Review and confirm your partnership details"
    # REVIEW PARTNERSHIPS DETAILS
    And I click on the link "edit"
    And I add "test partnership info change" to the inputfield "#edit-about-partnership"
    And I click on the button "#edit-next"
    Then the element "#edit-first-section" contains the text "test partnership info change"
    When I click on the button "html.js body.js-enabled main#content div div#block-par-theme-content form#par-flow-transition-partnership-details-overview.par-flow-transition-partnership-details-overview div fieldset#edit-authority-contacts.js-form-item.form-item.js-form-wrapper.form-wrapper.inline em.placeholder a.flow-link"
    And I add "Animal" to the inputfield "#edit-person-name"
    And I add "91723456789" to the inputfield "#edit-work-phone"
    And I add "9777777777" to the inputfield "#edit-mobile-phone"
    And I add "par_authority_animal@example.com" to the inputfield "#edit-email"
    When I click on the button "#edit-next"
    Then the element "#edit-authority-contacts" contains the text "Animal"
    And the element "#edit-authority-contacts" contains the text "par_authority_animal@example.com"
    And the element "#edit-authority-contacts" contains the text "91723456789"
    And the element "#edit-authority-contacts" contains the text "9777777777"
    When I click on the button "html.js body.js-enabled main#content div div#block-par-theme-content form#par-flow-transition-partnership-details-overview.par-flow-transition-partnership-details-overview div fieldset#edit-authority-contacts.js-form-item.form-item.js-form-wrapper.form-wrapper.inline div fieldset#edit-alternative-people.js-form-item.form-item.js-form-wrapper.form-wrapper.inline em.placeholder a.flow-link"
    And I add "Miss Piggy" to the inputfield "#edit-person-name"
    And I add "par_authority_piggy@example.com" to the inputfield "#edit-email"
    And I add "917234567899" to the inputfield "#edit-work-phone"
    And I add "97777777779" to the inputfield "#edit-mobile-phone"
    When I click on the button "#edit-next"
    Then the element "#edit-alternative-people" contains the text "Miss Piggy"
    And the element "#edit-alternative-people" contains the text "par_authority_piggy@example.com"
    And the element "#edit-alternative-people" contains the text "917234567899"
    And the element "#edit-alternative-people" contains the text "97777777779"
    When I click on the button "html.js body.js-enabled main#content div div#block-par-theme-content form#par-flow-transition-partnership-details-overview.par-flow-transition-partnership-details-overview div fieldset#edit-organisation-contacts.js-form-item.form-item.js-form-wrapper.form-wrapper.inline em.placeholder a.flow-link"
    And I add "Fozzie Bear" to the inputfield "#edit-person-name"
    And I add "91723456789" to the inputfield "#edit-work-phone"
    And I add "9777777777" to the inputfield "#edit-mobile-phone"
    And I add "par_business_fozzie@example.com" to the inputfield "#edit-email"
    And I click on the button "#edit-next"
    Then the element "#edit-organisation-contacts" contains the text "Fozzie Bear"
    And the element "#edit-organisation-contacts" contains the text "par_business_fozzie@example.com"
    And the element "#edit-organisation-contacts" contains the text "91723456789"
    And the element "#edit-organisation-contacts" contains the text "9777777777"
    When I click on the button "html.js body.js-enabled main#content div div#block-par-theme-content form#par-flow-transition-partnership-details-overview.par-flow-transition-partnership-details-overview div fieldset#edit-organisation-contacts.js-form-item.form-item.js-form-wrapper.form-wrapper.inline div fieldset#edit-alternative-people--2.js-form-item.form-item.js-form-wrapper.form-wrapper.inline em.placeholder a.flow-link"
    And I add "917234567899" to the inputfield "#edit-work-phone" 
    And I add "97777777779" to the inputfield "#edit-mobile-phone"
    And I add "Pepe the King Prawn" to the inputfield "#edit-person-name"
    And I add "par_business_pepe@example.com" to the inputfield "#edit-email"
    When I click on the button "#edit-next"
    Then the element "#edit-organisation-contacts" contains the text "par_business_pepe@example.com"
    And the element "#edit-organisation-contacts" contains the text "Pepe the King Prawn"
    And the element "#edit-organisation-contacts" contains the text "917234567899"
    And the element "#edit-organisation-contacts" contains the text "97777777779"
    And I click on the checkbox "#edit-confirmation"
    And I click on the button "#edit-next"
    Then the element "#block-par-theme-content" contains the text "confirmed_authority"
    When I click on the link "Review and confirm your inspection plan"
    Then the element "#edit-document-list" contains the text "Inspection Plan"
    And I click on the checkbox "#edit-document-list-12-confirm"
    And I click on the button "#edit-next"
    When I click on the link "Go back to your partnerships"
    Then the element "h1" contains the text "List of Partnerships for a Primary Authority"
    And I click on the link "Log out"
