<?php

/**
 * @file par_dashboards.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\user\Entity\User;


/**
 * Implements hook_form_alter().
 *
 * {@deprecated}
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function par_dashboards_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Views Exposed Filter customisation.
  if ($form['#id'] == 'views-exposed-form-par-data-transition-journey-1-step-1-dv-journey-1-step-1' ||
    $form['#id'] == 'views-exposed-form-rd-helpdesk-dashboard-par-rd-helpdesk-dashboard-page') {

    // Use class 'btn-link' to make a button look/act like a link.
    $form['actions']['submit']['#attributes']['class'][] = 'btn-link';
    $form['actions']['submit']['#value'] = 'Update results';

  }

}

/**
 * Implements hook_views_pre_render().
 *
 * {@deprecated}
 *
 * @param \Drupal\views\ViewExecutable $view
 */
function par_dashboards_views_pre_render(ViewExecutable $view) {

  // Customise RD Helpdesk Dashboard.
  if ($view->current_display == 'par_rd_helpdesk_dashboard_page') {

    // Override CSV Feed icon.
    $feed_icon = &$view->feedIcons[0];

    if (isset($feed_icon)) {

      // Get URL from Drupal Views Data Export module.
      $url = Url::fromUri($feed_icon['#url']);

      // Create link.
      $link = Link::fromTextAndUrl('Download as CSV', $url)->toString();

      // Feed icon as markup.
      $feed_icon = [
        '#type' => 'markup',
        '#markup' => $link,
        '#theme_wrappers' => [
          'container' => [
            '#attributes' => [
              'class' => ['views-data-export-csv-feed'],
            ],
          ],
        ],
      ];

    }

  }

}

/**
 * Implement hook_preprocess_views_view_field().
 */
function par_dashboards_preprocess_views_view_field(&$vars) {

  if ($vars['view']->id() != 'par_user_partnerships') {
    return;
  }

  $account = User::load(\Drupal::currentUser()->id());

  if ($vars['field']->getField() == '.authority_name') {
    if ($account->hasPermission('manage my authorities')) {
      // Convert the name into a link.
      $url = Url::fromRoute('par_partnership_flows.authority_details', ['par_data_partnership' => $vars['row']->id]);
      $link = Link::fromTextAndUrl(t($vars['field']->original_value->__toString()), $url);
      $vars['output'] = $link->toRenderable();
    }
  }

  if ($vars['field']->getField() == '.organisation_name') {
    if ($account->hasPermission('manage my organisations')) {
      // Convert the name into a link.
      $url = Url::fromRoute('par_partnership_flows.organisation_details', ['par_data_partnership' => $vars['row']->id]);
      $link = Link::fromTextAndUrl(t($vars['field']->original_value->__toString()), $url);
      $vars['output'] = $link->toRenderable();
    }
  }
}
