<?php

/**
 * @file
 * Contains par_validation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_error_handling_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_error_handling module.
    case 'help.page.par_error_handling':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds friendly handling of fatal errors and exceptions by displaying a page that users can understand.') . '</p>';
      return $output;

    default:
  }
}
