name: 'PAR Partnership Application Flows'
type: module
description: 'Creates the flows and components required to apply for a new partnership.'
core: 8.x
core_version_requirement: ^8 || ^9
package: PAR
dependencies:
  - par_data
  - par_flows
  - par_forms
