name: 'PAR Partnership Application Flows'
type: module
description: 'Creates the flows and components required to apply for a new partnership.'
core_version_requirement: ^9 || ^10
package: PAR
dependencies:
  - par_data
  - par_flows
  - par_forms
