<?php

/**
 * @file
 * Contains par_validation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_forms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_forms module.
    case 'help.page.par_forms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds all the necessary form builder components used to construct each form.') . '</p>';
      return $output;

    default:
  }
}
