features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
search_box: 0
govuk_cookie: 1
govuk_breadcrumb: 1
govuk_phase_banner: ''
phase_banner_message:
  value: ''
  format: basic_html
