par_data_classes:
  - par_data_advice
  - par_data_authority
  - par_data_enforcement_action
  - par_data_enforcement_notice
  - par_data_inspection_plan
  - par_data_legal_entity
  - par_data_organisation
  - par_data_partnership
  - par_date_person
  - par_data_premises
  - par_data_regulatory_function
  - par_data_sic_code
_core:
  default_config_hash: kBojBx0ohIgrlcuQVcAjtpsnaFcOeIo6eW967s4dO54
