enabled_matchers:
  zxcvbn_dictionarymatch: zxcvbn_dictionarymatch
  zxcvbn_datematch: '0'
  zxcvbn_digitmatch: '0'
  zxcvbn_l33tmatch: '0'
  zxcvbn_repeatmatch: '0'
  zxcvbn_sequencematch: '0'
  zxcvbn_spatialmatch: '0'
  zxcvbn_yearmatch: '0'
_core:
  default_config_hash: YeBe2Sr-ePva2qvjDyOI1kxGGr8by1JqcGGm6YINNnI
