_core:
  default_config_hash: YeBe2Sr-ePva2qvjDyOI1kxGGr8by1JqcGGm6YINNnI
enabled_matchers:
  zxcvbn_datematch: '0'
  zxcvbn_digitmatch: zxcvbn_digitmatch
  zxcvbn_l33tmatch: zxcvbn_l33tmatch
  zxcvbn_repeatmatch: '0'
  zxcvbn_sequencematch: zxcvbn_sequencematch
  zxcvbn_spatialmatch: '0'
  zxcvbn_yearmatch: '0'
  zxcvbn_dictionarymatch: zxcvbn_dictionarymatch
