session_limit_max: 1
session_limit_masquerade_ignore: true
session_limit_behaviour: 1
session_limit_logged_out_message_severity: warning
session_limit_roles:
  authenticated: 0
  administrator: 2
  par_authority: 0
  par_enforcement: 0
  par_organisation: 0
  par_helpdesk: 2
_core:
  default_config_hash: 6LIpKkpajaLVzp7vCiTE8WQxllcMEoQ3vrFIq4FRYSE
