_core:
  default_config_hash: FLJZME3II5fjmMSrdEvJHp95ZJf8V_X0jbX0VdVU1BU
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: XXX
    pass: XXX
allow_cli: true
debug_header: false
unset_basic_auth_headers: true
print: 'Auth required'
method: 0
paths: ''
allowlist: XXX
http_method_allowlist: {  }
domains: primary-authority.beis.gov.uk
