_core:
  default_config_hash: ls2wXvXf4vms4y6c-xMUgSp8ZmVmwFy5NgL0DIPgU_0
langcode: en
enabled: true
required_roles:
  authenticated: authenticated
  par_enforcement: par_enforcement
  par_authority: par_authority
  par_authority_manager: par_authority_manager
  par_organisation: par_organisation
  par_helpdesk: par_helpdesk
  senior_administration_officer: senior_administration_officer
  administrator: '0'
send_plugins: {  }
login_plugins: {  }
login_plugin_settings:
  tfa_trusted_browser:
    cookie_allow_subdomains: true
    cookie_expiration: 30
    cookie_name: tfa-trusted-browser
allowed_validation_plugins:
  tfa_recovery_code: tfa_recovery_code
  tfa_totp: tfa_totp
default_validation_plugin: tfa_totp
validation_plugin_settings:
  tfa_hotp:
    counter_window: 10
    site_name_prefix: 1
    name_prefix: TFA
    issuer: Drupal
  tfa_recovery_code:
    recovery_codes_amount: 10
  tfa_totp:
    time_skew: 2
    site_name_prefix: 1
    name_prefix: TFA
    issuer: Gov
validation_skip: 3
encryption: 2fa_test
tfa_flood_uid_only: 1
tfa_flood_window: 300
tfa_flood_threshold: 6
help_text: 'Contact support to reset your access'
mail:
  tfa_enabled_configuration:
    subject: 'Your [site:name] account now has two-factor authentication'
    body: "[user:display-name],\r\n\r\nThanks for configuring two-factor authentication on your [site:name] account!\r\n\r\nThis additional level of security will help to ensure that only you are able to log in to your account.\r\n\r\nIf you ever lose the device you configured, you should act quickly to delete its association with this account.\r\n\r\n--\r\n[site:name] team"
  tfa_disabled_configuration:
    subject: 'Your [site:name] account no longer has two-factor authentication'
    body: "[user:display-name],\r\n\r\nTwo-factor authentication has been disabled on your [site:name] account.\r\n\r\nIf you did not take this action, please contact a site administrator immediately.\r\n\r\n--\r\n[site:name] team"
