<?php

/**
 * @file
 * Contains par_enforcement_raise_flows.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_enforcement_raise_flows_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_enforcement_raise_flows module.
    case 'help.page.par_enforcement_raise_flows':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows coordinators to cease the membership of any member on their partnerships.') . '</p>';
      return $output;

    default:
  }
}
