applications:
  - name: beis-par-production
    routes:
      - route: primary-authority.beis.gov.uk
    buildpacks:
      - https://github.com/cloudfoundry/apt-buildpack#v0.2.3
      - php_buildpack
    memory: 2G
    disk_quota: 4096M
    timeout: 120
    services:
      - par-pg-production
      - par-redis-production
      - opss-log-drain
