applications:
  - name: beis-par-production
    routes:
      - route: primary-authority.beis.gov.uk
    buildpack: php_buildpack
    memory: 2G
    disk_quota: 10G
    timeout: 120
    services:
      - par-pg-production
      - par-redis-production
      - opss-log-drain
