applications:
  - name: ((app))
    routes:
      - route: ((app)).cloudapps.digital
    buildpack:
      - https://github.com/cloudfoundry/php-buildpack.git#v4.4.52
    memory: 2G
    disk_quota: 5G
    timeout: 120
