applications:
  - name: beis-par-staging
    routes:
      - route: beis-par-staging.cloudapps.digital
    buildpacks:
      - https://github.com/cloudfoundry/apt-buildpack#v0.2.3
      - php_buildpack
    memory: 2G
    disk_quota: 4096M
    timeout: 120
