<?php

/**
 * @file
 * Contains par_header.module.
 */
use Drupal\user\Entity\User;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;

/**
 * Implements hook_link_alter().
 */
function par_header_link_alter(&$variables) {

  /**
   * The URL of the link.
   *
   * @var Url
   */
  $url = $variables['url'];

  if ($url instanceof Url && $url->isRouted()) {
    if ($url->getRouteName() !== 'user.page') {
      return;
    }
    elseif ($variables['text'] == 'My account') {
      // Get current user.
      $user = User::load(\Drupal::currentUser()->id());

      // Override My Account link with username.
      $variables['text'] = t('@username', ['@username' => $user->get('name')->value]);
    }
  }

}
