<?php

/**
 * @file
 * Contains par_header.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_link_alter().
 */
function par_header_link_alter(&$variables) {

  /**
   * The URL of the link.
   *
   * @var Url
   */
  $url = $variables['url'];

  // Return early where possible.
  if ($url->isExternal()) {
    return;
  }
  else {
    $route_name = $url->getRouteName();
    if ($route_name != 'user.page') {
      return;
    }
    elseif ($variables['text'] == 'My account') {

      // get current user.
      $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());

      // override My Account link with username.
      $variables['text'] = t('@username', ['@username' => $user->get('name')->value]);

    }
  }

}
