<?php

/**
 * @file
 * Contains par_enquiry_view_flows.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function par_enquiry_view_flows_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the par_enquiry_view_flows module.
    case 'help.page.par_enquiry_view_flows':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows primary authority officers to view enquiries submitted by an enforcement officer.') . '</p>';
      return $output;

    default:
  }
}
