par_model.par_entity_type.*:
  type: config_entity
  label: 'PAR entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      lavel: 'Description'
    help:
      type: string
      label: 'Help'
    uuid:
      type: string
    description:
      type: string
      label: 'Description'
    help:
      type: string
      label: 'Help'
